### PR TITLE
feat: ability to set svc annotations

### PR DESCRIPTION
**Pull request by shanehull**
Adds the ability to set additional annotations on the Service resource.

### CODE REVIEW

**Comment by ChrisJBurns** [comment]
Thanks @shanehull  I'll try and give this a look so we can get it merged in. I may have to add CI tests into the Actions flow before we do merge this PR though just so we have as much assurance as possible.

**Comment by shanehull** [comment]
@ChrisJBurns let me know if there's anything we can do to get this merged. Currently we're blocked on using the chart, as we need annotations on the Service resource to be able to expose it.

**Review by ChrisJBurns — APPROVED** [review]

**Comment by ChrisJBurns** [comment]
@shanehull Yep apologies, just had a chance to go through my unreads. Have approved and run pipeline, and seems to be ok, however are you able to sign the commit?

**Comment by shanehull** [comment]
Done @ChrisJBurns.

**Comment by ChrisJBurns** [comment]
@shanehull I don't think the commit itself has been signed, you've added a signature to the commit message but the commit itself isn't signed with a key for more info: https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by shanehull** [comment]
Sorry @ChrisJBurns, should be verified now.

**Comment by ChrisJBurns** [comment]
Thanks @shanehull , merged!

**Pull request merged**
