### PR TITLE
Improve configuration

### PR DESCRIPTION
**Pull request by kxcasa**
PR to address the issue #2 :

- Given the DB configuration, which may use an external secret not managed by this chart, I don't see an elegant enough implementation to have the DB credentials in a secret file;
- Added the relevant configurations listed under https://docs.pact.io/pact_broker/configuration/settings#base_url and https://docs.pact.io/pact_broker/docker_images/pactfoundation#automatic-data-clean-up, setting as values the default ones according to the referred documentations;

### CODE REVIEW

**Review by ChrisJBurns — DISMISSED** [review]
Thank you for the @kbcasagrande  apologies for delay. Just got back from holiday this week :+1:

**Comment by ChrisJBurns** [comment]
@kbcasagrande Would you be able to squash and sign your commits? Also probably worth bumping up the minor version of the chart in this case as we are adding new backwards compatible features :+1:

**Comment by kxcasa** [comment]
> @kbcasagrande Would you be able to squash and sign your commits? Also probably worth bumping up the minor version of the chart in this case as we are adding new backwards compatible features +1

Commits squashed and signed: OK
Bump minor version: OK

**Review by ChrisJBurns — APPROVED** [review]

**Comment by ChrisJBurns** [comment]
@kbcasagrande  Merged! Feel free to give it a try on a cluster :+1:

**Pull request merged**
