### PR TITLE
feat: ability to run arbitrary sidecar extraContainers

### PR DESCRIPTION
**Pull request by roulettedares**
## adds the ability to run arbitrary sidecar extraContainers
i have a use case where i need to use [cloudsql proxy](https://github.com/GoogleCloudPlatform/cloud-sql-proxy) to connect the pact broker to a google cloudsql postgres instance.
```yaml
extraContainers:
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
    command:
      - /cloud_sql_proxy
      - '-instances=my-project:my-zone:my-db-name=tcp:5432'
      - '-enable_iam_login'
```
 another common use cases is running a vault sidecar to inject secrets

test values correctly output a new sidecar
```
        - command:
          - /cloud_sql_proxy
          - -instances=my-project:my-zone:my-db-name=tcp:5432
          - -enable_iam_login
          image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
          name: cloudsql-proxy
```

mostly copied from the common pattern at https://github.com/argoproj/argo-helm/blob/c08fc230d75c85b2c9a07138c5c7b7bc957b98df/charts/argo-cd/templates/argocd-repo-server/deployment.yaml

### CODE REVIEW

**Comment by roulettedares** [comment]
@ChrisJBurns fiddling with PGP to get my commits verified autoclosed and bugged out https://github.com/pact-foundation/pact-broker-chart/pull/46.

**Comment by ChrisJBurns** [comment]
@joshuasimon-taulia Will you be able to rebase your branch with `master`? When you've done this, we can get this merged in. Also could you update the issue description so it doesn't have the database password issue as this has been fixed with #43

**Comment by roulettedares** [comment]
> @joshuasimon-taulia Will you be able to rebase your branch with `master`? When you've done this, we can get this merged in. Also could you update the issue description so it doesn't have the database password issue as this has been fixed with #43

done and confirmed working

**Review by ChrisJBurns — APPROVED** [review]

**Comment by roulettedares** [comment]
thx!

**Pull request merged**
