### PR TITLE
enabled poddisruptionbudget in case more than one broker instance is used

### PR DESCRIPTION
**Pull request by sherifkayad**
enabled poddisruptionbudget in case more than one broker instance is used

### CODE REVIEW

**Comment by sherifkayad** [comment]
I will have a look at the linting tomorrow morning first thing. It might have to do with my VSCode

**Comment by sherifkayad** [comment]
@ChrisJBurns can you please have another look?

**Comment by ChrisJBurns** [comment]
@sherifkayad  Would you be able to bump the minor version as it's a new feature, I can approve and run the workflow once this is done 👍

**Comment by sherifkayad** [comment]
@ChrisJBurns done! thanks for the feedback.

**Comment by sherifkayad** [comment]
@ChrisJBurns can you help me identify why the linting is failing?

**Comment by sherifkayad** [comment]
locally helm lint is succeeding
image

**Comment by ChrisJBurns** [comment]
@sherifkayad I believe it's trailing whitespaces:
```
charts/pact-broker/values.yaml
  Error: 348:1 [trailing-spaces] trailing spaces
```

**Comment by sherifkayad** [comment]
Can we re-check now?

**Comment by sherifkayad** [comment]
@ChrisJBurns seems to be passing after my latest push 😅

**Review by ChrisJBurns — DISMISSED** [review]
lgtm

**Comment by ChrisJBurns** [comment]
@sherifkayad  One last thing, I've only just noticed, would you be able to sign your commit? The merging is blocked until this happens. The code changes are perfect, we just need to sign the commits

**Comment by sherifkayad** [comment]
can you check now? again did a sign-off and forced pushing

**Comment by ChrisJBurns** [comment]
@sherifkayad Sign-off is a great addition, but I was referring to [commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). Apologies for being a pain, but it does add a layer of security to the commits.

**Comment by sherifkayad** [comment]
@ChrisJBurns also done ;) there you go

image

**Review by ChrisJBurns — APPROVED** [review]

**Comment by ChrisJBurns** [comment]
@sherifkayad Thanks again! All merged :)

**Comment by sherifkayad** [comment]
Sure thing! Thanks for your time reviewing as well.

**Pull request merged**
