### PR TITLE
chore: /s/Pactflow/PactFlow

### PR DESCRIPTION
**Pull request by YOU54F**

### CODE REVIEW

**Comment by ChrisJBurns** [comment]
@YOU54F  need to bump the patch version of the chart

**Comment by YOU54F** [comment]
> @YOU54F need to bump the patch version of the chart

ahh nice one Chris, will do that now!

**Comment by ChrisJBurns** [comment]
@YOU54F you have some conflicts on your branch, do a quick rebase and we should be good to go!

**Comment by YOU54F** [comment]
Hey man, will sort, was waiting for brew to install helm and found the contributors guidelines, which were good and pointed me in the right location for everything I needed to change and run. Will drop change in tomorrow now 👍🏾 ta dude

**Comment by YOU54F** [comment]
Hopefully good to go now fella! 

As an aside got this running myself and impressed, nice job! Going to have a play around with it, with the PactFlow on prem image too :)

**Comment by ChrisJBurns** [comment]
@YOU54F Apologies for the request to rebase again :( We just merged a feature in so you'll need to merge the master branch into yours and just bump the patch version again and we can get this one in ASAP!

Am glad that it all works on your clusters too :)

**Comment by ChrisJBurns** [comment]
@YOU54F Whilst I've got some time over the Bank Holiday here in UK, thought I'd resolve some of the conflicts on this PR as we've had a fair few changes merged in since this PR was raised. Looks good, will approve and merge :+1:

**Review by ChrisJBurns — APPROVED** [review]

**Pull request merged**
