### PR TITLE
fix: make externalDatabase.config.auth.password work

### PR DESCRIPTION
**Pull request by roulettedares**
## fixes broken .Values.externalDatabase.config.auth.password
if `.Values.externalDatabase.enabled`, the current chart logic completely ignores `.Values.externalDatabase.config.auth.password` and incorrectly mounts `.Values.externalDatabase.config.auth.existingSecret`

### CODE REVIEW

**Comment by roulettedares** [comment]
Hi @ChrisJBurns. I noticed that you're currently reviewing https://github.com/pact-foundation/pact-broker-chart/pull/43 which fixes the broken `.Values.externalDatabase.config.auth.password` with some slightly different logic. which convention would you like me to follow? i basically just copy and pasted helper templates from the existing conventions in the chart.

**Comment by ChrisJBurns** [comment]
HI @joshuasimon-taulia thanks for the PR. You're correct, I'm currently reviewing the logic for the password changes but I need to make sure that we cover all scenarios. If you wanted to submit the container additions separately, we could get those in first :+1:

**Comment by roulettedares** [comment]
split extraContainers logic out to https://github.com/pact-foundation/pact-broker-chart/pull/46

**Comment by ChrisJBurns** [comment]
This has been fixed in https://github.com/pact-foundation/pact-broker-chart/pull/43

**Pull request closed without merging**
