### PR TITLE
fix: indentation on labels and annotations

### PR DESCRIPTION
**Pull request by daniel-maganto**
Fix indentation problem when add labels or annotations

### CODE REVIEW

**Comment by ChrisJBurns** [comment]
@daniel-maganto  Thank you for this!
You'll need to make the necessary bumps in the patch version (as shown in [lint logs](https://github.com/pact-foundation/pact-broker-chart/actions/runs/3909301231/jobs/6693419760))

**Comment by daniel-maganto** [comment]
Done! Updated to 0.4.1

**Comment by ChrisJBurns** [comment]
@daniel-maganto got some lint failures :( almost there 😄

**Comment by daniel-maganto** [comment]
Hope this one works! :D

**Review by ChrisJBurns — APPROVED** [review]
lgtm. thanks again @daniel-maganto

**Pull request merged**
